### ISSUE TITLE
Dependencies on old Input Manager

### ISSUE THREAD

**Issue by tacman** [PacktPublishing/Unity-2020-Virtual-Reality-Projects-3rd-Edition-#3]
A few scripts are still dependent on the old Input Manager, rather than the XR Interaction Toolkit, e.g.

Chapter07/Scripts/GlideLocomotionXRI.cs#L25-L26

```
        float forward = Input.GetAxis("XRI_Right_Primary2DAxis_Vertical");
        float sideways = Input.GetAxis("XRI_Right_Primary2DAxis_Horizontal");
```

I'll change the Player Input settings to Both, but I know there's a better solution.

The new XR Interaction Toolkit uses the new Input System, and prompts the user to switch to it when installing the package.

**Comment by linojon** [comment]
You are correct, use "Both" for the input system in Player Settings. The book and it's projects were published before Unity switched the XR Interaction Toolkit to the new input system (0.10). This was noted as a possibility early in the book but not included because the two packages didn't work together at the time. I will publish an addendum and update the GitHub projects after XR Interaction Toolkit 1.0 is officially released.

**Comment by MikeSparkes** [comment]
Hi Jonathan

Only on chapter 4, page 133 and stuck. Ethan will not follow the walk target when moving the arrows, the only thing I cannot figure out is what the Translate Gizmo is, maybe that has something to do with it?

Sorry a restart of Unity fixed it, still not sure what the translate gizmo is though!
